### ISSUE TITLE
Chezmoi breaks if config file has color: auto

### ISSUE THREAD

**Issue by rojosinalma** [twpayne/chezmoi#1326]
## Describe the bug

CM throws an error if the config file has the option `color` set in `auto`

## To reproduce

Add the option and try to do `chezmoi apply` or `chezmoi doctor`

## Expected behavior

No error is thrown. I suggest to fail silently or handle the case.

## Output of command with the `--verbose` flag

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ddabc4]

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/cmd.(*autoBool).Value(...)
	github.com/twpayne/chezmoi/v2/internal/cmd/autobool.go:57
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).persistentPreRunRootE(0x14000204000, 0x14000719400, 0x10584cae0, 0x0, 0x0, 0x1057bd3a0, 0x0)
	github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1151 +0x2dd4
github.com/spf13/cobra.(*Command).execute(0x14000719400, 0x10584cae0, 0x0, 0x0, 0x14000719400, 0x10584cae0)
	github.com/spf13/cobra@v1.2.1/command.go:835 +0x3ec
github.com/spf13/cobra.(*Command).ExecuteC(0x140000e6000, 0x140000e6000, 0x0, 0x0)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x264
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0x14000204000, 0x14000032050, 0x1, 0x1, 0x0, 0x0)
	github.com/twpayne/chezmoi/v2/internal/cmd/config.go:878 +0x70
github.com/twpayne/chezmoi/v2/internal/cmd.runMain(0x10507023c, 0x5, 0x105071500, 0x28, 0x1050713c0, 0x14, 0x105070df0, 0x8, 0x14000032050, 0x1, ...)
	github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:260 +0x94
github.com/twpayne/chezmoi/v2/internal/cmd.Main(0x10507023c, 0x5, 0x105071500, 0x28, 0x1050713c0, 0x14, 0x105070df0, 0x8, 0x14000032050, 0x1, ...)
	github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:87 +0x54
main.main()
	github.com/twpayne/chezmoi/v2/main.go:23 +0xec
```

## Output of `chezmoi doctor`

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104ddabc4]

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/cmd.(*autoBool).Value(...)
	github.com/twpayne/chezmoi/v2/internal/cmd/autobool.go:57
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).persistentPreRunRootE(0x14000204000, 0x14000719400, 0x10584cae0, 0x0, 0x0, 0x1057bd3a0, 0x0)
	github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1151 +0x2dd4
github.com/spf13/cobra.(*Command).execute(0x14000719400, 0x10584cae0, 0x0, 0x0, 0x14000719400, 0x10584cae0)
	github.com/spf13/cobra@v1.2.1/command.go:835 +0x3ec
github.com/spf13/cobra.(*Command).ExecuteC(0x140000e6000, 0x140000e6000, 0x0, 0x0)
	github.com/spf13/cobra@v1.2.1/command.go:974 +0x264
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.2.1/command.go:902
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0x14000204000, 0x14000032050, 0x1, 0x1, 0x0, 0x0)
	github.com/twpayne/chezmoi/v2/internal/cmd/config.go:878 +0x70
github.com/twpayne/chezmoi/v2/internal/cmd.runMain(0x10507023c, 0x5, 0x105071500, 0x28, 0x1050713c0, 0x14, 0x105070df0, 0x8, 0x14000032050, 0x1, ...)
	github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:260 +0x94
github.com/twpayne/chezmoi/v2/internal/cmd.Main(0x10507023c, 0x5, 0x105071500, 0x28, 0x1050713c0, 0x14, 0x105070df0, 0x8, 0x14000032050, 0x1, ...)
	github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:87 +0x54
main.main()
	github.com/twpayne/chezmoi/v2/main.go:23 +0xec
```

**Comment by twpayne** [comment]
Thank you so much for spotting and reporting this!

**Comment by rojosinalma** [comment]
Weird thing is that this didn't happen in 1.8.x.
I just upgraded from last year and this happened.

**Comment by twpayne** [comment]
chezmoi v2 was pretty much a complete internal re-write, including the config file and command line parsing, so there certainly would have been a few inadvertent bugs introduced.

**Comment by rojosinalma** [comment]
Ah gotcha. 

Thanks for fixing it quickly anyway!
