### ISSUE TITLE
Allow `file://` in url for `.chezmoiexternal.yaml`

### ISSUE THREAD

**Issue by felipecrs** [twpayne/chezmoi#1745]
## Is your feature request related to a problem? Please describe.

So that I can do something like:

```console
"etc/sudoers.d/{{ .non_root_user }}":
  type: file
  url: file:///dev/null
  filter:
    command: echo
    args: ["{{ .non_root_user }}  ALL=(ALL) NOPASSWD:ALL"]
```

## Describe the solution you'd like

Allow `file://` in url for `.chezmoiexternal.yaml`

## Describe alternatives you've considered

To use script. But then I lack chezmoi's diff output.

## Additional context

This is what happens currently if I try:

```console
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x757ff7]

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/chezmoilog.LogHTTPRequest(0x11df938, 0xc000136000, 0xc000614100)
        github.com/twpayne/chezmoi/v2/internal/chezmoilog/chezmoilog.go:119 +0x1d7
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*SourceState).getExternalDataRaw(0xc0005023c0, {0x11df938, 0xc000136000}, {{0xc0001204f8, 0x18}}, {{0xc0007649fc, 0x4}, 0x0, 0x0, 0x0, ...}, ...)
        github.com/twpayne/chezmoi/v2/internal/chezmoi/sourcestate.go:1169 +0x3aa
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*SourceState).getExternalData(0xc0005023c0, {0x11df938, 0xc000136000}, {{0xc0001204f8, 0x20}}, {{0xc0007649fc, 0x4}, 0x0, 0x0, 0x0, ...}, ...)
        github.com/twpayne/chezmoi/v2/internal/chezmoi/sourcestate.go:1205 +0x88
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*SourceState).readExternalFile.func1()
        github.com/twpayne/chezmoi/v2/internal/chezmoi/sourcestate.go:1795 +0x65
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*lazyContents).Contents(0xc000032f00)
        github.com/twpayne/chezmoi/v2/internal/chezmoi/lazy.go:47 +0x3f
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*TargetStateFile).EntryState(0xc0004080b0, 0x12)
        github.com/twpayne/chezmoi/v2/internal/chezmoi/targetstateentry.go:135 +0x2c
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*SourceState).Apply(0xc0005023c0, {0x11f6620, 0xc000480800}, {0x11f6620, 0xc000480800}, {0x11ec728, 0xc000478360}, {{0x1a36998, 0x0}}, {{0xc000120e28, ...}}, ...)
        github.com/twpayne/chezmoi/v2/internal/chezmoi/sourcestate.go:530 +0x36d
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).applyArgs(0xc00027c000, {0x11df938, 0xc000136000}, {0x11f6620, 0xc000480800}, {{0x1a36998, 0xc0000340f0}}, {0xc0004e7e90, 0x0, 0x3}, ...)
        github.com/twpayne/chezmoi/v2/internal/cmd/config.go:584 +0x705
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).runApplyCmd(0x5a2500, 0xc00079fc00, {0xc0004e7e90, 0x0, 0x0})
        github.com/twpayne/chezmoi/v2/internal/cmd/applycmd.go:40 +0x150
github.com/spf13/cobra.(*Command).execute(0xc000253180, {0xc0004e7e60, 0x3, 0x3})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000252280)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0xc00079fe00, {0xc000126010, 0x4, 0x4})
        github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1085 +0x78
github.com/twpayne/chezmoi/v2/internal/cmd.runMain({{0x11bbacc, 0x5}, {0x11d6a80, 0x28}, {0x11bf340, 0x14}, {0x11bc4c0, 0x8}}, {0xc000126010, 0x4, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:289 +0x151
github.com/twpayne/chezmoi/v2/internal/cmd.Main({{0x11bbacc, 0x5}, {0x11d6a80, 0x28}, {0x11bf340, 0x14}, {0x11bc4c0, 0x8}}, {0xc000126010, 0x4, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:100 +0xc9
main.main()
        github.com/twpayne/chezmoi/v2/main.go:26 +0x125
```

**Comment by twpayne** [comment]
5b50963e1467040ee1c6f97f9cb64b7576085f3b fixes the panic.

This looks like an abuse of the filter system of externals to modify an empty input to then set the file's contents using an `echo` command, using the fact that `.chezmoiexternal.yaml` is interpreted as a template.

chezmoi already has a system for generating files with contents that vary: templates. Instead, consider creating `etc/sudoers.d/filename.tmpl` in the source directory containing

    {{ .non_root_user }}  ALL=(ALL) NOPASSWD:ALL

**Comment by felipecrs** [comment]
The problem is that the name of the file is also variadic:

```
etc/sudoers.d/{{ .non_root_user }}
```

Happy to hear if there are better suggestions...

**Comment by felipecrs** [comment]
I would prefer not to use symlinks, but to create a real file in the destination as not all the programs support reading from symlinks.

By the way, the panic is indeed fixed. Now the output states that `file://` protocol is not supported.

```console
> chezmoi apply
chezmoi: Get "file:///dev/null": unsupported protocol scheme "file"
chezmoi: exit status 1
```

For what it seems, the use case that I used as example isn't a good one. But I can see this feature as a way to allow copying files in chezmoi, allowing the destination path to be variadic.

If I think on more concrete examples I will post them here.
