### ISSUE TITLE
Chezmoi commands randomly fail when having ignores on script files

### ISSUE THREAD

**Issue by mhofstetter** [twpayne/chezmoi#2000]
First of all: Thank you for chezmoi & keep up the good work!

## Describe the bug

Since chezmoi 2.15, executing chezmoi commands (status, apply, ...) randomly fails with the error `fatal error: concurrent map writes`.

## To reproduce

Create a bunch of scripts in `.chezmoiscripts` and a `.chezmoiignore` file with an ignore on some scriptfiles. (e.g. ignoring scripts from a different OS)

Executing commands (e.g. `chezmoi status`) fails due to parallel visitation of the script files in combination with writing ignored files/dirs to the map `ignoredRelPaths`. (for the newly introduced command `chezmoi ignored` in 2.15)

## Expected behavior

No concurrent map writes errors.

## Output of command with the `--verbose` flag

<details>

```console
❯ chezmoi --verbose status
fatal error: concurrent map writes

goroutine 30 [running]:
runtime.throw({0x104b6046a?, 0x10452c094?})
	runtime/panic.go:992 +0x50 fp=0x14000075c70 sp=0x14000075c40 pc=0x104134b60
runtime.mapassign_faststr(0x140005de3f0?, 0x14000520ba0?, {0x14000520ba0, 0x2b})
	runtime/map_faststr.go:212 +0x3bc fp=0x14000075ce0 sp=0x14000075c70 pc=0x104112c9c
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).readScriptsDir.func2({0x140005f8050?, 0x0?}, {{0x1400019e400?, 0x1?}}, {0x104f574f8, 0x1400049fd40}, {0x0, 0x0})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/sourcestate.go:2077 +0x414 fp=0x14000075e90 sp=0x14000075ce0 pc=0x10452c0b4
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir.func1({0x104f56228, 0x14000112300})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:249 +0xe0 fp=0x14000075f40 sp=0x14000075e90 pc=0x10452f220
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir.func3()
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:274 +0x30 fp=0x14000075f60 sp=0x14000075f40 pc=0x10452f120
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x64 fp=0x14000075fd0 sp=0x14000075f60 pc=0x104502c34
runtime.goexit()
	runtime/asm_arm64.s:1259 +0x4 fp=0x14000075fd0 sp=0x14000075fd0 pc=0x1041677d4
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x90

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0x140001be638?)
	runtime/sema.go:56 +0x2c
sync.(*WaitGroup).Wait(0x140005294c8)
	sync/waitgroup.go:136 +0x88
golang.org/x/sync/errgroup.(*Group).Wait(0x140005294c0)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x30
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir({0x104f55a80, 0x1400003a0c8}, {0x104f59928, 0x14000529100}, {{0x140005a8c00?, 0x0?}}, 0x1400053bcb0)
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:281 +0x318
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).readScriptsDir(0x14000596000, {0x104f55a80, 0x1400003a0c8}, {{0x140005a8c00?, 0x140005a89ed?}})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/sourcestate.go:2091 +0x13c
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Read.func2({{0x140005a8c00?, 0x3c?}}, {0x104f574f8, 0x1400049f790}, {0x0?, 0x0?})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/sourcestate.go:879 +0x620
github.com/twpayne/chezmoi/v2/pkg/chezmoi.walkSourceDir({0x104f59928, 0x14000529100}, {{0x140005a8c00?, 0x1?}}, {0x104f574f8, 0x1400049f790}, 0x140001bf0d0)
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:196 +0x60
github.com/twpayne/chezmoi/v2/pkg/chezmoi.walkSourceDir({0x104f59928, 0x14000529100}, {{0x14000520240?, 0x14000520240?}}, {0x104f574f8, 0x140000a44e0}, 0x140001bf0d0)
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:223 +0x234
github.com/twpayne/chezmoi/v2/pkg/chezmoi.WalkSourceDir({0x104f59928, 0x14000529100}, {{0x14000520240?, 0x1400007c040?}}, 0x140001bf0d0)
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:175 +0x94
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*SourceState).Read(0x14000596000, {0x104f55a80, 0x1400003a0c8}, 0x140005d24b0)
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/sourcestate.go:929 +0x184
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).newSourceState(0x14000392a80, {0x104f55a80, 0x1400003a0c8}, {0x0, 0x0, 0x140001bfb98?})
	github.com/twpayne/chezmoi/v2/pkg/cmd/config.go:1420 +0xbbc
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).makeRunEWithSourceState.func1(0x14000568a00, {0x14000533570, 0x0, 0x1})
	github.com/twpayne/chezmoi/v2/pkg/cmd/config.go:1220 +0x5c
github.com/spf13/cobra.(*Command).execute(0x14000568a00, {0x14000533560, 0x1, 0x1})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x4c4
github.com/spf13/cobra.(*Command).ExecuteC(0x14000223b80)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0x1400072fdf0?, {0x140000320d0, 0x2, 0x2})
	github.com/twpayne/chezmoi/v2/pkg/cmd/config.go:1096 +0x70
github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0x104d9d6bc, 0x6}, {0x104d9e140, 0x28}, {0x104d9dfc0, 0x14}, {0x104d9df70, 0x8}}, {0x140000320d0, 0x2, ...})
	github.com/twpayne/chezmoi/v2/pkg/cmd/cmd.go:266 +0xe0
github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0x104d9d6bc, 0x6}, {0x104d9e140, 0x28}, {0x104d9dfc0, 0x14}, {0x104d9df70, 0x8}}, {0x140000320d0?, 0x200000003?, ...})
	github.com/twpayne/chezmoi/v2/pkg/cmd/cmd.go:128 +0x54
main.main()
	github.com/twpayne/chezmoi/v2/main.go:26 +0xd8

goroutine 39 [semacquire]:
sync.runtime_Semacquire(0x14000143da8?)
	runtime/sema.go:56 +0x2c
sync.(*WaitGroup).Wait(0x14000112448)
	sync/waitgroup.go:136 +0x88
golang.org/x/sync/errgroup.(*Group).Wait(0x14000112440)
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x30
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir({0x104f55a48, 0x14000529480}, {0x104f59928, 0x14000529100}, {{0x140005f8050?, 0x140005e8410?}}, 0x1400053bcb0)
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:281 +0x318
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir.func1({0x104f56228, 0x14000529400})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:255 +0x15c
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir.func3()
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:274 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x90

goroutine 31 [runnable]:
path.Join({0x140002d6000, 0x2, 0x0?})
	path/path.go:179 +0xa8
github.com/twpayne/chezmoi/v2/pkg/chezmoi.AbsPath.Join({{0x140005f8050?, 0x0?}}, {0x14000194f28, 0x1, 0x0?})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/abspath.go:76 +0xd0
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir.func1({0x104f56228, 0x14000112340})
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:244 +0x84
github.com/twpayne/chezmoi/v2/pkg/chezmoi.concurrentWalkSourceDir.func3()
	github.com/twpayne/chezmoi/v2/pkg/chezmoi/system.go:274 +0x30
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x90
```
</details>

## Output of `chezmoi doctor`

<details>

```console
❯ chezmoi doctor
RESULT   CHECK                MESSAGE
ok       version              v2.15.0, commit 702cc4db2e19ebd246df58a54522d30959d18cd5, built at 2022-04-03T20:20:01Z, built by Homebrew
ok       latest-version       v2.15.0
ok       os-arch              darwin/arm64
ok       uname                Darwin marco-mbp 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:47:26 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T8101 arm64
ok       go-version           go1.18 (gc)
ok       executable           /opt/homebrew/bin/chezmoi
ok       upgrade-method       brew-upgrade
ok       config-file          ~/.config/chezmoi/chezmoi.yaml
ok       source-dir           ~/.local/share/chezmoi is a directory
ok       suspicious-entries   no suspicious entries
ok       working-tree         ~/.local/share/chezmoi is a directory
ok       dest-dir             ~ is a directory
ok       shell-command        found /bin/zsh
ok       shell-args           /bin/zsh
ok       cd-command           found /bin/zsh
ok       cd-args              /bin/zsh
ok       edit-command         found /opt/homebrew/bin/nvim
ok       edit-args            /opt/homebrew/bin/nvim
info     diff-command         not set
ok       umask                022
ok       git-command          found /opt/homebrew/bin/git, version 2.35.1
ok       merge-command        found /usr/bin/vimdiff
info     age-command          age not found in $PATH
ok       gpg-command          found /usr/local/bin/gpg, version 2.2.26
info     pinentry-command     not set
info     1password-command    op not found in $PATH
info     bitwarden-command    bw not found in $PATH
info     gopass-command       gopass not found in $PATH
info     keepassxc-command    keepassxc-cli not found in $PATH
info     keepassxc-db         not set
info     lastpass-command     lpass not found in $PATH
info     pass-command         pass not found in $PATH
info     vault-command        vault not found in $PATH
info     secret-command       not set
```

</details>

**Comment by twpayne** [comment]
Great catch and fix. Thank you very much indeed!
