### ISSUE TITLE
Seg fault when running `chezmoi update` 

### ISSUE THREAD

**Issue by evanrichards** [twpayne/chezmoi#3031]
## Describe the bug

Seg fault when running `chezmoi update` 

## To reproduce

```
$ gh repo clone twpayne/chezmoi
$ cd chezmoi
$ make
$ ./chezmoi
```

## Expected behavior

Pull and apply any data

## Output of command with the `--verbose` flag

```console
$ ./chezmoi update -v
Already up to date.
unexpected fault address 0x12dc1c008
fatal error: fault
[signal SIGBUS: bus error code=0x1 addr=0x12dc1c008 pc=0x1048eb56c]

goroutine 1 [running]:
runtime.throw({0x10521b84e?, 0x10568d480?})
        /usr/local/go/src/runtime/panic.go:1047 +0x40 fp=0x1400091f3a0 sp=0x1400091f370 pc=0x104545fc0
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:838 +0x10c fp=0x1400091f3e0 sp=0x1400091f3a0 pc=0x10455db6c
go.etcd.io/bbolt.(*freelist).read(0x0?, 0x0?)
        /Users/evanrichards/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/freelist.go:266 +0x1c fp=0x1400091f490 sp=0x1400091f3f0 pc=0x1048eb56c
go.etcd.io/bbolt.(*DB).loadFreelist.func1()
        /Users/evanrichards/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:415 +0xac fp=0x1400091f4c0 sp=0x1400091f490 pc=0x1048e673c
sync.(*Once).doSlow(0x1400002ba88?, 0x105691a80?)
        /usr/local/go/src/sync/once.go:74 +0x104 fp=0x1400091f520 sp=0x1400091f4c0 pc=0x104584024
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:65
go.etcd.io/bbolt.(*DB).loadFreelist(0x1400002b8c0?)
        /Users/evanrichards/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:408 +0x48 fp=0x1400091f550 sp=0x1400091f520 pc=0x1048e6668
go.etcd.io/bbolt.Open({0x14000414600, 0x37}, 0x414600?, 0x1400017a388)
        /Users/evanrichards/go/pkg/mod/go.etcd.io/bbolt@v1.3.7/db.go:290 +0x3a0 fp=0x1400091f620 sp=0x1400091f550 pc=0x1048e6070
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*BoltPersistentState).open(0x1400017a360)
        /Users/evanrichards/code/chezmoi/pkg/chezmoi/boltpersistentstate.go:228 +0x80 fp=0x1400091f6b0 sp=0x1400091f620 pc=0x104a63ce0
github.com/twpayne/chezmoi/v2/pkg/chezmoi.(*BoltPersistentState).Get(0x1400017a360, {0x105fe2fd8, 0xb, 0xb}, {0x105fe2ff8, 0xb, 0xb})
        /Users/evanrichards/code/chezmoi/pkg/chezmoi/boltpersistentstate.go:186 +0x48 fp=0x1400091f730 sp=0x1400091f6b0 pc=0x104a637b8
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).applyArgs(0x140001c8c80, {0x1057c13a0, 0x14000198018}, {0x1057c7b10, 0x140001df380}, {{0x14000040035?, 0x0?}}, {0x14000531600, 0x0, 0x1}, ...)
        /Users/evanrichards/code/chezmoi/pkg/cmd/config.go:522 +0x134 fp=0x1400091f910 sp=0x1400091f730 pc=0x1051ccc94
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runUpdateCmd(0x140001c8c80, 0x14000336f00, {0x14000531600, 0x0, 0x1})
        /Users/evanrichards/code/chezmoi/pkg/cmd/updatecmd.go:93 +0x408 fp=0x1400091fae0 sp=0x1400091f910 pc=0x105204c58
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).runUpdateCmd-fm(0x14000336f00?, {0x14000531600?, 0x1?, 0x1?})
        <autogenerated>:1 +0x40 fp=0x1400091fb20 sp=0x1400091fae0 pc=0x1052107a0
github.com/spf13/cobra.(*Command).execute(0x14000336f00, {0x140005315e0, 0x1, 0x1})
        /Users/evanrichards/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8 fp=0x1400091fc60 sp=0x1400091fb20 pc=0x1046ca518
github.com/spf13/cobra.(*Command).ExecuteC(0x14000390900)
        /Users/evanrichards/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c fp=0x1400091fd20 sp=0x1400091fc60 pc=0x1046cac6c
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/evanrichards/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/twpayne/chezmoi/v2/pkg/cmd.(*Config).execute(0x1400091fde8?, {0x140001960a0, 0x2, 0x2})
        /Users/evanrichards/code/chezmoi/pkg/cmd/config.go:1126 +0x6c fp=0x1400091fd40 sp=0x1400091fd20 pc=0x1051d0a2c
github.com/twpayne/chezmoi/v2/pkg/cmd.runMain({{0x0, 0x0}, {0x1055079d5, 0x28}, {0x105507a0d, 0x14}, {0x0, 0x0}}, {0x140001960a0, 0x2, ...})
        /Users/evanrichards/code/chezmoi/pkg/cmd/cmd.go:285 +0x194 fp=0x1400091fe30 sp=0x1400091fd40 pc=0x1051c8934
github.com/twpayne/chezmoi/v2/pkg/cmd.Main({{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}}, {0x140001960a0?, 0x1400005ea00?, ...})
        /Users/evanrichards/code/chezmoi/pkg/cmd/cmd.go:108 +0x54 fp=0x1400091fec0 sp=0x1400091fe30 pc=0x1051c7bb4
main.main()
        /Users/evanrichards/code/chezmoi/main.go:26 +0xd4 fp=0x1400091ff70 sp=0x1400091fec0 pc=0x105213bd4
runtime.main()
        /usr/local/go/src/runtime/proc.go:250 +0x248 fp=0x1400091ffd0 sp=0x1400091ff70 pc=0x104548608
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400091ffd0 sp=0x1400091ffd0 pc=0x104579d44

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x1400007afa0 sp=0x1400007af80 pc=0x104548a34
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:305 +0xb8 fp=0x1400007afd0 sp=0x1400007afa0 pc=0x104548878
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400007afd0 sp=0x1400007afd0 pc=0x104579d44
created by runtime.init.6
        /usr/local/go/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x1400007b760 sp=0x1400007b740 pc=0x104548a34
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /usr/local/go/src/runtime/mgcsweep.go:319 +0x110 fp=0x1400007b7b0 sp=0x1400007b760 pc=0x1045353c0
runtime.gcenable.func1()
        /usr/local/go/src/runtime/mgc.go:178 +0x28 fp=0x1400007b7d0 sp=0x1400007b7b0 pc=0x104529e78
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400007b7d0 sp=0x1400007b7d0 pc=0x104579d44
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:178 +0x74

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x140000a4000?, 0x1054f20e0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x1400007bf50 sp=0x1400007bf30 pc=0x104548a34
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:387
runtime.(*scavengerState).park(0x1060bc400)
        /usr/local/go/src/runtime/mgcscavenge.go:400 +0x5c fp=0x1400007bf80 sp=0x1400007bf50 pc=0x1045331dc
runtime.bgscavenge(0x0?)
        /usr/local/go/src/runtime/mgcscavenge.go:633 +0xac fp=0x1400007bfb0 sp=0x1400007bf80 pc=0x1045337bc
runtime.gcenable.func2()
        /usr/local/go/src/runtime/mgc.go:179 +0x28 fp=0x1400007bfd0 sp=0x1400007bfb0 pc=0x104529e18
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400007bfd0 sp=0x1400007bfd0 pc=0x104579d44
created by runtime.gcenable
        /usr/local/go/src/runtime/mgc.go:179 +0xb8

goroutine 18 [finalizer wait]:
runtime.gopark(0x1400007a5a8?, 0x10451ebb0?, 0xc0?, 0x89?, 0x10648ca90?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x1400007a580 sp=0x1400007a560 pc=0x104548a34
runtime.runfinq()
        /usr/local/go/src/runtime/mfinal.go:193 +0x10c fp=0x1400007a7d0 sp=0x1400007a580 pc=0x104528f0c
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x1400007a7d0 sp=0x1400007a7d0 pc=0x104579d44
created by runtime.createfing
        /usr/local/go/src/runtime/mfinal.go:163 +0x84

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000076740 sp=0x14000076720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140000767d0 sp=0x14000076740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000767d0 sp=0x140000767d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000114740 sp=0x14000114720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140001147d0 sp=0x14000114740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001147d0 sp=0x140001147d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000076f40 sp=0x14000076f20 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x14000076fd0 sp=0x14000076f40 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000076fd0 sp=0x14000076fd0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x1d9a03634a2f?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000114f40 sp=0x14000114f20 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x14000114fd0 sp=0x14000114f40 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000114fd0 sp=0x14000114fd0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x1d9a03642201?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000115740 sp=0x14000115720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140001157d0 sp=0x14000115740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001157d0 sp=0x140001157d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x1d9a0363fce5?, 0x3?, 0x2f?, 0xe?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000115f40 sp=0x14000115f20 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x14000115fd0 sp=0x14000115f40 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000115fd0 sp=0x14000115fd0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 21 [GC worker (idle)]:
runtime.gopark(0x1060f89c0?, 0x3?, 0x5d?, 0xa0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000077740 sp=0x14000077720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140000777d0 sp=0x14000077740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000777d0 sp=0x140000777d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x1d9a03634a59?, 0x3?, 0x29?, 0x10?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000116740 sp=0x14000116720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140001167d0 sp=0x14000116740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001167d0 sp=0x140001167d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 22 [GC worker (idle)]:
runtime.gopark(0x1060f89c0?, 0x1?, 0xf3?, 0x12?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000077f40 sp=0x14000077f20 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x14000077fd0 sp=0x14000077f40 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000077fd0 sp=0x14000077fd0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 39 [GC worker (idle)]:
runtime.gopark(0x1d9a0363461e?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000116f40 sp=0x14000116f20 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x14000116fd0 sp=0x14000116f40 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x14000116fd0 sp=0x14000116fd0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 23 [GC worker (idle)]:
runtime.gopark(0x1d9a03634671?, 0x0?, 0x0?, 0x0?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000078740 sp=0x14000078720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140000787d0 sp=0x14000078740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140000787d0 sp=0x140000787d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28

goroutine 40 [GC worker (idle)]:
runtime.gopark(0x1d9a03634935?, 0x1?, 0x32?, 0xbd?, 0x0?)
        /usr/local/go/src/runtime/proc.go:381 +0xe4 fp=0x14000117740 sp=0x14000117720 pc=0x104548a34
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1275 +0xec fp=0x140001177d0 sp=0x14000117740 pc=0x10452bdbc
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm64.s:1172 +0x4 fp=0x140001177d0 sp=0x140001177d0 pc=0x104579d44
created by runtime.gcBgMarkStartWorkers
        /usr/local/go/src/runtime/mgc.go:1199 +0x28a
```

## Output of `chezmoi doctor`

<details>

```console
$ ./chezmoi doctor
RESULT    CHECK                MESSAGE
warning   version              dev, commit 1aeb5ac437079034173625ef5bf3507939b1388b, built at 2023-06-09T08:23:42Z
warning   latest-version       v2.34.0
ok        os-arch              darwin/arm64
ok        uname                Darwin Evans-MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:53:19 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6020 arm64
ok        go-version           go1.20.5 (gc)
ok        executable           ~/code/chezmoi/chezmoi
ok        upgrade-method       replace-executable
ok        config-file          ~/.config/chezmoi/chezmoi.toml, last modified 2023-06-08T20:06:25-07:00
ok        source-dir           ~/.local/share/chezmoi is a git working tree (clean)
warning   suspicious-entries   ~/.local/share/chezmoi/private_dot_config/chezmoi/private_chezmoistate.boltdb
ok        working-tree         ~/.local/share/chezmoi is a git working tree (clean)
ok        dest-dir             ~ is a directory
ok        umask                022
ok        cd-command           found /bin/zsh
ok        cd-args              /bin/zsh
info      diff-command         not set
ok        edit-command         found /opt/homebrew/bin/nvim
ok        edit-args            /opt/homebrew/bin/nvim
ok        git-command          found /usr/bin/git, version 2.39.2
ok        merge-command        found /opt/homebrew/bin/nvim
ok        shell-command        found /bin/zsh
ok        shell-args           /bin/zsh
info      age-command          age not found in $PATH
ok        gpg-command          found /opt/homebrew/bin/gpg, version 2.4.2
info      pinentry-command     not set
info      1password-command    op not found in $PATH
info      bitwarden-command    bw not found in $PATH
info      dashlane-command     dcli not found in $PATH
info      gopass-command       gopass not found in $PATH
info      keepassxc-command    keepassxc-cli not found in $PATH
info      keepassxc-db         not set
info      keeper-command       keeper not found in $PATH
info      lastpass-command     lpass not found in $PATH
info      pass-command         pass not found in $PATH
info      passhole-command     ph not found in $PATH
info      rbw-command          rbw not found in $PATH
info      vault-command        vault not found in $PATH
info      secret-command       not set

```

</details>

**Comment by twpayne** [comment]
This is a SIGBUS (bus error), not a SEGFAULT (segmentation fault).

I note that the output of `chezmoi doctor` includes:

    warning   suspicious-entries   ~/.local/share/chezmoi/private_dot_config/chezmoi/private_chezmoistate.boltdb

This means that you're managing chezmoi's persistent state database with chezmoi, which will cause serious problems. I suspect that this means that chezmoi's persistent state database is being truncated while chezmoi is using it, leading to an out-of-bounds mmap access, which triggers a SIGBUS.

The solution is to remove the `~/.local/share/chezmoi/private_dot_config/chezmoi` directory.

**Comment by evanrichards** [comment]
champion
