### ISSUE TITLE
Error when adding a remove attribute

### ISSUE THREAD

**Issue by drod3763** [twpayne/chezmoi#3282]
## Describe the bug

It throws an error when trying to add a remove attribute to a dotfile

## To reproduce

1. Open terminal in home folder
2. `chezmoi add ~/.zshrc` if you haven't already done so
3. `chezmoi chattr remove ~/.zshrc`

## Expected behavior

Adds the `.zshrc` file with the remove attribute

## Output of command with the `--verbose` flag

```console
$ chezmoi chattr --verbose remove ~/.zshrc
panic: 1: unknown source file type

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/cmd.(*modifier).modifyFileAttr(0x1400059e0c0, {{0x1400077e1b8, 0x6}, 0x1, {0x0, 0x0}, 0x0, 0x0, 0x0, 0x0, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/chattrcmd.go:564 +0x54c
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).runChattrCmd(0x14000412000, 0x14000325b00?, {0x1400007cab0, 0x2, 0x3}, 0x140003f4f00)
        github.com/twpayne/chezmoi/v2/internal/cmd/chattrcmd.go:204 +0x3a4
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).newChattrCmd.(*Config).makeRunEWithSourceState.func2(0x1400080ee00?, {0x1400007cab0, 0x2, 0x3})
        github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1496 +0x88
github.com/spf13/cobra.(*Command).execute(0x14000325b00, {0x1400007c990, 0x3, 0x3})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x14000395800)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0x1400071fd08?, {0x140001c4010, 0x4, 0x4})
        github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1185 +0x70
github.com/twpayne/chezmoi/v2/internal/cmd.runMain({{0x105bb14a0, 0x6}, {0x105bb26a0, 0x28}, {0x105bb2440, 0x14}, {0x105bb2350, 0x8}}, {0x140001c4010, 0x4, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:297 +0x180
github.com/twpayne/chezmoi/v2/internal/cmd.Main({{0x105bb14a0, 0x6}, {0x105bb26a0, 0x28}, {0x105bb2440, 0x14}, {0x105bb2350, 0x8}}, {0x140001c4010?, 0x4, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:109 +0x60
main.main()
        github.com/twpayne/chezmoi/v2/main.go:26 +0xd8
```

## Output of `chezmoi doctor`

```console
$ chezmoi doctor
RESULT    CHECK                       MESSAGE
ok        version                     v2.40.0, commit 6a8ca1634654734bb33a036ffb9c21e6b9f4d28d, built at 2023-09-19T08:14:08Z, built by Homebrew
ok        latest-version              v2.40.0
ok        os-arch                     darwin/arm64
ok        uname                       Darwin P6H9DQX16L 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64
ok        go-version                  go1.21.1 (gc)
ok        executable                  /opt/homebrew/bin//chezmoi
ok        upgrade-method              brew-upgrade
ok        config-file                 ~/.config/chezmoi/chezmoi.toml, last modified 2023-10-04T09:02:11-04:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /opt/homebrew/bin/code
ok        edit-args                   code --new-window
ok        git-command                 found /opt/homebrew/bin/git, version 2.42.0
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
ok        age-command                 found /opt/homebrew/bin/age, version 1.1.1
ok        gpg-command                 found /opt/homebrew/bin/gpg, version 2.4.3
info      pinentry-command            not set
ok        1password-command           found /opt/homebrew/bin/op, version 2.21.0
info      bitwarden-command           bw not found in $PATH
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
info      keepassxc-command           keepassxc-cli not found in $PATH
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
ok        lastpass-command            found /opt/homebrew/bin/lpass, version 1.3.6
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
info      secret-command              not set
```

</details>

## Additional context

I moved my zsh files into `.config/zsh` so I want to remove the extra .zshrc when I apply my dotfiles. Trying to do that with the command doesn't seem to work.

**Comment by halostatue** [comment]
When the build on #3283 is complete, you should be able to try an artifact from there.
