### ISSUE TITLE
chezmoi can not be started on termux

### ISSUE THREAD

**Issue by Kreijstal** [twpayne/chezmoi#3507]
## Describe the bug
Using the chezmoi install script ` sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply $GITHUB_USERNAME` and it failed, so I decided to look it up and found https://github.com/twpayne/chezmoi/issues/445 and another issues tried their workarounds but still fails, chezmoi standalone simply does not start.

## To reproduce
use ` sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply $GITHUB_USERNAME` in termux

## Expected behavior

It does not crash.

## Output of command with the `--verbose` flag

chezmoi or chezmoi --verbose make no difference in output. It prints the same stack trace.
```console
$ ./chezmoi --verbose
```

## Output of `chezmoi doctor`

<details>
chezmoi or chezmoi doctor does not work. Same result
```console
$ chezmoi doctor
```

```
SIGSYS: bad system call                                                                                                                                                                         PC=0x15fb0 m=0 sigcode=1
PC=0x15fb0 m=0 sigcode=1

goroutine 1 [syscall, locked to thread]:
syscall.Syscall6(0x4000116000?, 0x38?, 0x38?, 0x4000116040?, 0x0?, 0x4f?, 0xffffffffffffff9c?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/syscall/syscall_linux.go:91 +0x2c fp=0x40000f7b90 sp=0x40000f7b00 pc=0x9509c
syscall.faccessat2(0x4000116000?, {0x4000116000?, 0x759ce12c40?}, 0x1, 0xc0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/syscall/zsyscall_linux_arm64.go:33 +0x84 fp=0x40000f7c00 sp=0x40000f7b90 pc=0x90fe4
syscall.Faccessat(0x4000116000?, {0x4000116000, 0x38}, 0x1, 0x200)
        /opt/hostedtoolcache/go/1.21.6/x64/src/syscall/syscall_linux.go:167 +0x3c fp=0x40000f7cf0 sp=0x40000f7c00 pc=0x8e63c
internal/syscall/unix.Eaccess(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/internal/syscall/unix/eaccess_linux.go:10
os/exec.findExecutable({0x4000116000, 0x38})
        /opt/hostedtoolcache/go/1.21.6/x64/src/os/exec/lp_unix.go:31 +0x58 fp=0x40000f7d40 sp=0x40000f7cf0 pc=0x211948
os/exec.LookPath({0x12c1aa0, 0x14})
        /opt/hostedtoolcache/go/1.21.6/x64/src/os/exec/lp_unix.go:71 +0x1b8 fp=0x40000f7de0 sp=0x40000f7d40 pc=0x211c18
github.com/atotto/clipboard.init.0()
        /home/runner/go/pkg/mod/github.com/atotto/clipboard@v0.1.4/clipboard_unix.go:80 +0x318 fp=0x40000f7e00 sp=0x40000f7de0 pc=0xe65848
runtime.doInit1(0x1fa4e70)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:6740 +0xd4 fp=0x40000f7f30 sp=0x40000f7e00 pc=0x59134
runtime.doInit(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:6707
runtime.main()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:249 +0x374 fp=0x40000f7fd0 sp=0x40000f7f30 pc=0x4b264
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000f7fd0 sp=0x40000f7fd0 pc=0x7d4a4

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x400006ef90 sp=0x400006ef70 pc=0x4b5d8
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:404
runtime.forcegchelper()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:322 +0xb8 fp=0x400006efd0 sp=0x400006ef90 pc=0x4b468
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x400006efd0 sp=0x400006efd0 pc=0x7d4a4
created by runtime.init.6 in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:310 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x400006f760 sp=0x400006f740 pc=0x4b5d8
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgcsweep.go:280 +0xa0 fp=0x400006f7b0 sp=0x400006f760 pc=0x37380
runtime.gcenable.func1()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:200 +0x28 fp=0x400006f7d0 sp=0x400006f7b0 pc=0x2be98
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x400006f7d0 sp=0x400006f7d0 pc=0x7d4a4
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x400007e000?, 0x15b98d8?, 0x1?, 0x0?, 0x4000002d00?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x400006ff50 sp=0x400006ff30 pc=0x4b5d8
runtime.goparkunlock(...)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x2089180)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgcscavenge.go:425 +0x5c fp=0x400006ff80 sp=0x400006ff50 pc=0x34c4c
runtime.bgscavenge(0x0?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgcscavenge.go:653 +0x44 fp=0x400006ffb0 sp=0x400006ff80 pc=0x35194
runtime.gcenable.func2()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:201 +0x28 fp=0x400006ffd0 sp=0x400006ffb0 pc=0x2be38
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x400006ffd0 sp=0x400006ffd0 pc=0x7d4a4
created by runtime.gcenable in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mgc.go:201 +0xac

goroutine 5 [finalizer wait]:
runtime.gopark(0x400006e5b8?, 0x40000a8090?, 0xe8?, 0xe5?, 0x7615bc?)
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/proc.go:398 +0xc8 fp=0x400006e580 sp=0x400006e560 pc=0x4b5d8
runtime.runfinq()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mfinal.go:193 +0x108 fp=0x400006e7d0 sp=0x400006e580 pc=0x2af48
runtime.goexit()
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/asm_arm64.s:1197 +0x4 fp=0x400006e7d0 sp=0x400006e7d0 pc=0x7d4a4
created by runtime.createfing in goroutine 1
        /opt/hostedtoolcache/go/1.21.6/x64/src/runtime/mfinal.go:163 +0x80

r0      0xffffffffffffff9c
r1      0x4000116080
r2      0x1
r3      0x200
r4      0x0
r5      0x0
r6      0x0
r7      0x1
r8      0x1b7
r9      0x2f7273752f73656c
r10     0x2f7273752f73656c
r11     0x6d7265742f6e6962
r12     0x6270696c632d7875
r13     0x7465732d6472616f
r14     0x3
r15     0x5e02db61555a
r16     0x40000f63a0
r17     0x40000f7c80
r18     0x0
r19     0xc4793a4f875d164a
r20     0x7fcdf98fd0
r21     0x2089fe0
r22     0x4000004000
r23     0x8e41dc0be9fcd734
r24     0xf060d7b75027bdc5
r25     0x5383edcd67c06036
r26     0x40000f79d0
r27     0x1
r28     0x40000021a0
r29     0x40000f7a98
lr      0x15f6c
sp      0x40000f7aa0
pc      0x15fb0
fault   0x0
~/bin $ file chezmoi
chezmoi: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=3UaC1pNtG7p7VuILQb2f/Ga5nel4GXcxwpC8vIOKz/dpd89vBMKDTa0VEsyexR/xvVTVSKKJGpjwAx_c1Ic, stripped
~/bin 
```

</details>

**Comment by twpayne** [comment]
This looks like https://github.com/golang/go/issues/60125.

Are you trying to run a Linux chezmoi executable on an Android device?

**Comment by twpayne** [comment]
So, I'm pretty sure what's happening is that you're running a `linux/arm64` binary on Android. Since Go 1.20, such binaries no longer run on Android.

#3508 adds a build of chezmoi for Android (Termux) which should fix the issue here.

In the short term, you can install chezmoi on Termux with:

    pkg install chezmoi

**Comment by Kreijstal** [comment]
Hi, yes, correct this is android.
