### ISSUE TITLE
chezmoi apply :: SIGSEGV :: 1.5.6 :: macOS

### ISSUE THREAD

**Issue by yamamoto-hiroki** [twpayne/chezmoi#353]
Running 'chezmoi apply' returns a 'SIGSEGV'. It looks like it has to do with inconsistent referencing 'once_' / 'run_once_' ? Removing the 'run_once_' prefixed script fixes the issue, however the use case requires the use of the 'run_once_' functionality provided by chezmoi. See below for output.

```
computer% pwd
/Users/username/.local/share/chezmoi
computer% ls -l                                                
total 32
-rw-r--r--  1 username  staff  36 Jun 16 18:00 run_050_giraffe
-rw-r--r--  1 username  staff  37 Jun 16 18:00 run_150_elephant
-rw-r--r--  1 username  staff  34 Jun 16 18:00 run_once_100_miauw.sh
computer% for file in $(ls); do echo "$file::"; cat $file; echo ''; done
run_050_giraffe::
#!/usr/bin/env bash

echo 'giraffe'

run_150_elephant::
#!/usr/bin/env bash

echo 'elephant'

run_once_100_miauw.sh::
#!/usr/bin/env bash

echo 'miauw'

computer% chezmoi apply
giraffe
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x137a696]

goroutine 1 [running]:
github.com/twpayne/chezmoi/lib/chezmoi.(*Script).Apply(0xc0000589c0, 0x17700a0, 0x1bd2800, 0x176c1c0, 0xc00007a440, 0xc000058a20, 0x0, 0x0)
	/home/travis/gopath/src/github.com/twpayne/chezmoi/lib/chezmoi/script.go:105 +0x936
github.com/twpayne/chezmoi/lib/chezmoi.(*TargetState).Apply(0xc0001425a0, 0x17700a0, 0x1bd2800, 0x176c1c0, 0xc00007a440, 0xc000058a20, 0x1bb6c00, 0x1e006d0)
	/home/travis/gopath/src/github.com/twpayne/chezmoi/lib/chezmoi/targetstate.go:156 +0xe8
github.com/twpayne/chezmoi/cmd.(*Config).applyArgs(0x1bad700, 0x17700a0, 0x1bd2800, 0x1bd2a58, 0x0, 0x0, 0x176c1c0, 0xc00007a440, 0xc000119d70, 0xc000119cf8)
	/home/travis/gopath/src/github.com/twpayne/chezmoi/cmd/config.go:147 +0x3b0
github.com/twpayne/chezmoi/cmd.(*Config).runApplyCmd(0x1bad700, 0x17700a0, 0x1bd2800, 0x1bd2a58, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/twpayne/chezmoi/cmd/apply.go:23 +0x14f
github.com/twpayne/chezmoi/cmd.makeRunE.func1(0x1ba83e0, 0x1bd2a58, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/twpayne/chezmoi/cmd/config.go:420 +0x5b
github.com/spf13/cobra.(*Command).execute(0x1ba83e0, 0x1bd2a58, 0x0, 0x0, 0x1ba83e0, 0x1bd2a58)
	/home/travis/gopath/pkg/mod/github.com/0robustus1/cobra@v0.0.4-0.20190522074606-64400adf086c/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x1ba8fc0, 0x0, 0x0, 0x15360d3)
	/home/travis/gopath/pkg/mod/github.com/0robustus1/cobra@v0.0.4-0.20190522074606-64400adf086c/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/pkg/mod/github.com/0robustus1/cobra@v0.0.4-0.20190522074606-64400adf086c/command.go:800
github.com/twpayne/chezmoi/cmd.Execute()
	/home/travis/gopath/src/github.com/twpayne/chezmoi/cmd/root.go:112 +0x2e
main.main()
	/home/travis/gopath/src/github.com/twpayne/chezmoi/main.go:6 +0x20
computer% 
```

**Comment by twpayne** [comment]
Thanks very much for the bug report, this indeed looks like a bug in chezmoi.

Please could you post the output of `chezmoi doctor`.

Thanks!

**Comment by yamamoto-hiroki** [comment]
```
computer% chezmoi doctor
     ok: version 1.5.6, commit 377bed96d1854380103b05fbee701a05d8ae1af5, built at 2019-06-06T23:53:47Z
     ok: /Users/username/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/username (destination directory, perm 755)
     ok: /Users/username/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.20.1)
       : /usr/local/bin/gpg: could not extract version from "gpg (GnuPG/MacGPG2) 2.2.10\nlibgcrypt 1.8.3\nCopyright (C) 2018 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n\nHome: /Users/keisenberg/.gnupg\nSupported algorithms:\nPubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA\nCipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,\n        CAMELLIA128, CAMELLIA192, CAMELLIA256\nHash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224\nCompression: Uncompressed, ZIP, ZLIB, BZIP2\n"
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by yamamoto-hiroki** [comment]
```
computer% chezmoi doctor
     ok: version 1.5.6, commit 377bed96d1854380103b05fbee701a05d8ae1af5, built at 2019-06-06T23:53:47Z
     ok: /Users/username/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/username (destination directory, perm 755)
     ok: /Users/username/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/bin/vi (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/bin/git (source VCS command, version 2.20.1)
       : /usr/local/bin/gpg: could not extract version from "gpg (GnuPG/MacGPG2) 2.2.10\nlibgcrypt 1.8.3\nCopyright (C) 2018 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law.\n\nHome: /Users/username/.gnupg\nSupported algorithms:\nPubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA\nCipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,\n        CAMELLIA128, CAMELLIA192, CAMELLIA256\nHash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224\nCompression: Uncompressed, ZIP, ZLIB, BZIP2\n"
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

**Comment by twpayne** [comment]
Thank you very much for providing this information. I added a few tests to try to reproduce the problem in #357, but could not re-create the bug.

Could you run these tests on your machine (by checking out the chezmoi repo and then running `go test ./...`) and report the output? Do you have any ideas as what might be not working?

**Comment by twpayne** [comment]
Doing some more digging in to this, it looks like chezmoi is somehow failing to create the database where it stores which scripts have been run, but isn't noticing this.

Please could you post the output of the following command:

    find ~/.config/chezmoi -ls

**Comment by DandyDev** [comment]
I'm having the same problem. Output of `chezmoi doctor`:

```
λ ~/ chezmoi doctor
     ok: version 1.5.8, commit c829084445a6464fd73cc3e54297d958d34b6f81, built at 2019-06-22T21:38:48Z
     ok: /Users/daan/.local/share/chezmoi (source directory, perm 700)
     ok: /Users/daan (destination directory, perm 755)
warning: /Users/daan/.config/chezmoi/chezmoi.toml (configuration file)
     ok: /usr/local/bin/code (editor)
     ok: /usr/bin/vimdiff (merge command)
     ok: /usr/local/bin/git (source VCS command, version 2.22.0)
warning: gpg (GnuPG, not found)
warning: op (1Password CLI, not found)
warning: bw (Bitwarden CLI, not found)
warning: keepassxc-cli (KeePassXC CLI, not found)
warning: lpass (LastPass CLI, not found)
warning: pass (pass CLI, not found)
warning: vault (Vault CLI, not found)
```

Output of `find ~/.config/chezmoi -ls`:

```
λ ~/ find ~/.config/chezmoi -ls
find: /Users/daan/.config/chezmoi: No such file or directory
```

**Comment by DandyDev** [comment]
Tests all pass:

```
λ ~/projects/tools/chezmoi/ master go test ./...
?   	github.com/twpayne/chezmoi	[no test files]
ok  	github.com/twpayne/chezmoi/cmd	1.393s
?   	github.com/twpayne/chezmoi/internal/extract-helps	[no test files]
?   	github.com/twpayne/chezmoi/internal/extract-markdown-ast	[no test files]
?   	github.com/twpayne/chezmoi/internal/generate-goreleaser-yaml	[no test files]
ok  	github.com/twpayne/chezmoi/lib/chezmoi	0.080s
```

**Comment by DandyDev** [comment]
Update: the panic goes away when I add a `chezmoi.toml` to `~/.config/chezmoi`. It seems that `chezmoi apply` expects a config file to be present when there are `run_*` scripts. `chezmoi init` does _not_ automatically create the `~/.config/chezmoi` dir, nor does it create `chezmoi.toml`, unless you pass a repo to `chezmoi init` and have a `.chezmoi.<format>.tmpl` file in that repo.

I'm now confronted with another error though: 

```
chezmoi: fork/exec /var/folders/jw/r8_jn30j40321xjs8vt7911h0000gn/T/bla.sh075263331: exec format error
```

The script `run_once_bla.sh` is executable and contains only one line: `echo "This works"`

Hope this helps!

**Comment by DandyDev** [comment]
Another update: adding a shebang to the script, fixes the second error. Might wanna add to the docs that a shebang is expected for scripts.

**Comment by twpayne** [comment]
Thanks very much for the investigation @DandyDev - I can now duplicate the problem and have a fix.

**Comment by DandyDev** [comment]
Great!
