### ISSUE TITLE
Automated push to chezmoi.io fails with permission denied error

### ISSUE THREAD

**Issue by twpayne** [twpayne/chezmoi#3622]
## Describe the bug

Tagging a new version of chezmoi should push the new website to the `gh-pages` branch. However, this [currently fails](https://github.com/twpayne/chezmoi/actions/runs/8126585452/job/22211016818) with the error:

```
INFO    -  Copying '/home/runner/work/chezmoi/chezmoi/assets/chezmoi.io/site' to 'gh-pages' branch and pushing to GitHub.
remote: Permission to twpayne/chezmoi.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/twpayne/chezmoi/': The requested URL returned error: 403
Traceback (most recent call last):
  File "/home/runner/.local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/__main__.py", line 316, in gh_deploy_command
    gh_deploy.gh_deploy(
  File "/home/runner/.local/lib/python3.10/site-packages/mkdocs/commands/gh_deploy.py", line 1[29](https://github.com/twpayne/chezmoi/actions/runs/8126585452/job/22211016818#step:6:30), in gh_deploy
    ghp_import.ghp_import(
  File "/home/runner/.local/lib/python3.10/site-packages/ghp_import.py", line 285, in ghp_import
    git.check_call('push', opts['remote'], opts['branch'])
  File "/home/runner/.local/lib/python3.10/site-packages/ghp_import.py", line 119, in check_call
    sp.check_call(['git'] + list(args), **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line [36](https://github.com/twpayne/chezmoi/actions/runs/8126585452/job/22211016818#step:6:37)9, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'push', 'origin', 'gh-pages']' returned non-zero exit status 128.
Error: Process completed with exit code 1.
```

## To reproduce

Tag a new version of chezmoi.

## Expected behavior

The new chezmoi.io pages should be pushed without error.

## Output of command with the `--verbose` flag

n/a

## Output of `chezmoi doctor`

n/a

## Additional context

I'm not sure when this stopped working. It might be related to the use of fine-grained GitHub Action permissions.

**Comment by twpayne** [comment]
Should be fixed by #3623.
