### ISSUE TITLE
`chezmoi chattr +encrypted` with external files cause panic

### ISSUE THREAD

**Issue by Ra2-IFV** [twpayne/chezmoi#4012]
## Describe the bug

`chezmoi chattr +encrypted` on external files, cause segfault

## To reproduce

```bash
$ chezmoi chattr --debug --verbose +encrypted /external/file
time=1970-01-01T00:00:00.001-00:00 level=INFO msg=persistentPreRunRootE version.version=2.52.4 version.commit="" version.date=2024-10-10T12:20:02Z version.builtBy="" args="[chezmoi chattr --debug --verbose +encrypted /external/file]" goVersion=go1.23.2
time=1970-01-01T00:00:00.001-00:00 level=INFO msg=Stat component=system name=/chezmoi
time=1970-01-01T00:00:00.001-00:00 level=INFO msg=Stat component=system name=/chezmoi/.git
time=1970-01-01T00:00:00.002-00:00 level=INFO msg=ReadFile component=system name=/chezmoi/.chezmoiroot size=5 data="home\n"
time=1970-01-01T00:00:00.002-00:00 level=INFO msg=ReadFile component=system name=/chezmoi/.chezmoiversion size=7 data="2.52.3\n"
time=1970-01-01T00:00:00.002-00:00 level=INFO msg=Stat component=system name=/chezmoi/home
time=1970-01-01T00:00:00.002-00:00 level=INFO msg=Stat component=system name=/chezmoi/home
time=1970-01-01T00:00:00.002-00:00 level=INFO msg=ReadDir component=system name=/chezmoi/home
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57c5a5cd8740]

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/chezmoi.(*SourceStateFile).Contents(...)
	/build/chezmoi/src/chezmoi-2.52.4/internal/chezmoi/sourcestateentry.go:164
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).runChattrCmd(0xc0006f4008, 0x57c5a76d40c0?, {0xc00037db40, 0x2, 0x4}, 0xc0000ed860)
	/build/chezmoi/src/chezmoi-2.52.4/internal/cmd/chattrcmd.go:201 +0x620
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).newChattrCmd.(*Config).makeRunEWithSourceState.func2(0xc0006fc308, {0xc00037db40, 0x2, 0x4})
	/build/chezmoi/src/chezmoi-2.52.4/internal/cmd/config.go:1611 +0x85
github.com/spf13/cobra.(*Command).execute(0xc0006fc308, {0xc00037db00, 0x4, 0x4})
	/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0006fa008)
	/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/build/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0xc000931de0?, {0xc0000401f0, 0x5, 0x5})
	/build/chezmoi/src/chezmoi-2.52.4/internal/cmd/config.go:1244 +0x78
github.com/twpayne/chezmoi/v2/internal/cmd.runMain({{0x57c5a61cacd0, 0x6}, {0x0, 0x0}, {0x57c5a61cbd70, 0x14}, {0x0, 0x0}}, {0xc0000401f0, 0x5, ...})
	/build/chezmoi/src/chezmoi-2.52.4/internal/cmd/cmd.go:271 +0x22a
github.com/twpayne/chezmoi/v2/internal/cmd.Main({{0x57c5a61cacd0, 0x6}, {0x0, 0x0}, {0x57c5a61cbd70, 0x14}, {0x0, 0x0}}, {0xc0000401f0, 0x5, ...})
	/build/chezmoi/src/chezmoi-2.52.4/internal/cmd/cmd.go:107 +0xa5
main.main()
	/build/chezmoi/src/chezmoi-2.52.4/main.go:30 +0x107
```

## Expected behavior

Should throw an non-critical error

## Output of command with the `--verbose` flag

See above.

## Output of `chezmoi doctor`

nil

## Additional context

`chezmoi chattr +remove external exact...` will throw error: `chezmoi: rename /chezmoi/folder/create_empty_ /chezmoi/folder/create_: no such file or directory`

**Comment by twpayne** [comment]
Thanks for spotting this. #4015 should fix it.
