### ISSUE TITLE
`chezmoi secret keyring` throws error

### ISSUE THREAD

**Issue by twio142** [twpayne/chezmoi#4038]
## Describe the bug

Any child command of `chezmoi secret keyring` causes the same error:

```
panic: set: persistent state mode not set

goroutine 1 [running]:
github.com/twpayne/chezmoi/v2/internal/cmd.getAnnotations(0x14000aa2f08)
        github.com/twpayne/chezmoi/v2/internal/cmd/annotation.go:50 +0x10c
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).persistentPreRunRootE(0x1400087a008, 0x14000aa2f08, {0x140005cf988?, 0x104669510?, 0x14000a98b00?})
        github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1932 +0x30
github.com/spf13/cobra.(*Command).execute(0x14000aa2f08, {0x140006348e0, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.1/command.go:956 +0x718
github.com/spf13/cobra.(*Command).ExecuteC(0x1400078af08)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/twpayne/chezmoi/v2/internal/cmd.(*Config).execute(0x140005cfdd0?, {0x1400013e130, 0x5, 0x5})
        github.com/twpayne/chezmoi/v2/internal/cmd/config.go:1253 +0x70
github.com/twpayne/chezmoi/v2/internal/cmd.runMain({{0x10576ed90, 0x6}, {0x10576fb50, 0x8}, {0x10576fc40, 0x14}, {0x10576fb60, 0x8}}, {0x1400013e130, 0x5, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:341 +0x178
github.com/twpayne/chezmoi/v2/internal/cmd.Main({{0x10576ed90, 0x6}, {0x10576fb50, 0x8}, {0x10576fc40, 0x14}, {0x10576fb60, 0x8}}, {0x1400013e130?, 0x1044146f4?, ...})
        github.com/twpayne/chezmoi/v2/internal/cmd/cmd.go:114 +0x54
main.main()
        github.com/twpayne/chezmoi/v2/main.go:30 +0xe8
```

## To reproduce

`chezmoi secret keyring get / set / delete ...`

## Output of `chezmoi doctor`

```
RESULT    CHECK                       MESSAGE
ok        version                     v2.53.0, commit Homebrew, built at 2024-10-26T19:35:19Z, built by Homebrew
ok        latest-version              v2.53.0
ok        os-arch                     darwin/arm64
ok        uname                       Darwin user.local 24.0.0 Darwin Kernel Version 24.0.0: Tue Sep 24 23:37:13 PDT 2024; root:xnu-11215.1.12~1/RELEASE_ARM64_T8112 arm64
ok        go-version                  go1.23.2 (gc)
ok        executable                  /opt/homebrew/bin/chezmoi
ok        upgrade-method              brew-upgrade
ok        config-file                 ~/.config/chezmoi/chezmoi.json, last modified 2024-10-15T19:15:16+02:00
warning   source-dir                  ~/.local/share/chezmoi is a git working tree (dirty)
ok        suspicious-entries          no suspicious entries
warning   working-tree                ~/.local/share/chezmoi is a git working tree (dirty)
ok        dest-dir                    ~ is a directory
ok        umask                       022
ok        cd-command                  found /bin/zsh
ok        cd-args                     /bin/zsh
info      diff-command                not set
ok        edit-command                found /opt/homebrew/bin/nvim
ok        edit-args                   nvim
ok        git-command                 found /opt/homebrew/bin/git, version 2.47.0
ok        merge-command               found /usr/bin/vimdiff
ok        shell-command               found /bin/zsh
ok        shell-args                  /bin/zsh
info      age-command                 age not found in $PATH
ok        gpg-command                 found /opt/homebrew/bin/gpg, version 2.4.5
info      pinentry-command            not set
info      1password-command           op not found in $PATH
ok        bitwarden-command           found /opt/homebrew/bin/bw, version 2024.6.0
info      bitwarden-secrets-command   bws not found in $PATH
info      dashlane-command            dcli not found in $PATH
info      doppler-command             doppler not found in $PATH
info      gopass-command              gopass not found in $PATH
ok        keepassxc-command           found /opt/homebrew/bin/keepassxc-cli, version 2.7.9
info      keepassxc-db                not set
info      keeper-command              keeper not found in $PATH
info      lastpass-command            lpass not found in $PATH
info      pass-command                pass not found in $PATH
info      passhole-command            ph not found in $PATH
info      rbw-command                 rbw not found in $PATH
info      vault-command               vault not found in $PATH
info      vlt-command                 vlt not found in $PATH
ok        secret-command              found /opt/homebrew/bin/chezmoi

```

**Comment by twpayne** [comment]
Thanks for reporting. This is fixed in #4039 and I'll release a new version.
